### ISSUE TITLE
install gurobipy failed

### ISSUE THREAD

**Issue by hwz9612** [quantumiracle/nash-dqn#1]
Hi,
When I install gurobipy 9.5.2, I found the following problem.
`ERROR: Could not find a version that satisfies the requirement gurobipy==9.5.2`
Can you encounter the problem? What should I DO?

**Comment by quantumiracle** [comment]
Hi, the Gurobipy package will not be used unless you wanna test with this solver. The default solver is ECOS. You can comment out this dependency.

**Comment by hwz9612** [comment]
Hi,
Now I don't install the gurobipy. But I encountered another problem. Just as the following,
`D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py:21: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  module = self._system_import(name, *args, **kwargs)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/doctor/DR_TWO/experiment/morvanzhou/contents/nash-dqn/launch.py", line 1, in <module>
    import supersuit, gym
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\supersuit\__init__.py", line 1, in <module>
    from .generic_wrappers import *  # NOQA
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\supersuit\generic_wrappers\__init__.py", line 1, in <module>
    from .frame_skip import frame_skip_v0  # NOQA
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\supersuit\generic_wrappers\frame_skip.py", line 2, in <module>
    from supersuit.utils.wrapper_chooser import WrapperChooser
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\supersuit\utils\wrapper_chooser.py", line 1, in <module>
    import gym
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\gym\__init__.py", line 4, in <module>
    from gym.core import (
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\gym\core.py", line 7, in <module>
    from gym import spaces
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\gym\spaces\__init__.py", line 1, in <module>
    from gym.spaces.space import Space
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\gym\spaces\space.py", line 13, in <module>
    import numpy as np
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\numpy\__init__.py", line 230, in <module>
    import mkl
  File "D:\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\mkl\__init__.py", line 49, in <module>
    from . import _mklinit
ImportError: cannot import name '_mklinit' from 'mkl' (C:\ProgramData\Anaconda3\envs\env_name\lib\site-packages\mkl\__init__.py)`
Can you meet with the problem?
Thanks.

**Comment by quantumiracle** [comment]
Hi it seems the error message is not related to `gurobipy` but `mkl`?
