### ISSUE TITLE
OSError: rom boxing is not installed

### ISSUE THREAD

**Issue by hwz9612** [quantumiracle/nash-dqn#3]
Hi,
Now I encountered the new problem. Just as the following shows,
`Traceback (most recent call last):
  File "/home/heweizhen/exper_code/nash-dqn/launch.py", line 169, in <module>
    env = eval(args.env_name).parallel_env(obs_type=obs_type, full_action_space=False, auto_rom_install_path=None)
  File "/home/heweizhen/anaconda3/envs/exper_env/lib/python3.9/site-packages/pettingzoo/utils/conversions.py", line 12, in par_fn
    env = env_fn(**kwargs)
  File "/home/heweizhen/anaconda3/envs/exper_env/lib/python3.9/site-packages/pettingzoo/atari/base_atari_env.py", line 17, in env_fn
    env = raw_env_fn(**kwargs)
  File "/home/heweizhen/anaconda3/envs/exper_env/lib/python3.9/site-packages/pettingzoo/atari/boxing_v2.py", line 7, in raw_env
    return BaseAtariEnv(
  File "/home/heweizhen/anaconda3/envs/exper_env/lib/python3.9/site-packages/pettingzoo/atari/base_atari_env.py", line 26, in BaseAtariEnv
    return parallel_to_aec_wrapper(ParallelAtariEnv(**kwargs))
  File "/home/heweizhen/anaconda3/envs/exper_env/lib/python3.9/site-packages/pettingzoo/atari/base_atari_env.py", line 95, in __init__
    raise OSError(
OSError: rom boxing is not installed. Please install roms using AutoROM tool (https://github.com/Farama-Foundation/AutoROM) or specify and double-check the path to your Atari rom using the `rom_path` argument.`
What can I do?
Thanks.

**Comment by quantumiracle** [comment]
Hi, 

Did you install using Poetry and still have the problem? 
There is this autorom package you need to install: [https://github.com/Farama-Foundation/AutoROM](https://github.com/Farama-Foundation/AutoROM)
